version: '3'
services:
  # PostgreSQL container
  postgres:
    image: postgres:latest
    container_name: my-postgres
    environment:
      POSTGRES_DB: your-database
      POSTGRES_USER: your-username
      POSTGRES_PASSWORD: your-password
    ports:
      - "5432:5432"

  # Spring Boot container
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: backend/target/your-spring-boot-app.jar
    container_name: my-spring-boot
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/your-database
      SPRING_DATASOURCE_USERNAME: your-username
      SPRING_DATASOURCE_PASSWORD: your-password

  # React container
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        FRONTEND: frontend
    container_name: my-react-app
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - backend
